manual update of Taiwan.csv for 2022-01-04.
The PDF released on 202-01-05 (containing stats for 2022-01-04)
shows this error again:

    ValueError: There are some unknown columns: Index(['廠牌 劑次', '1/4 接種人次', '累計至 1/4 接種人次'], dtype='object')

Previously: b9bd39a9477dde087287f6307fa4d01b62e4aa78 and 67d5d3e1ab497d935c2d70da56aa0ed9cb4959bf